#!/bin/sh
set -e

# Compile the circuit
npx circom circuit.circom --r1cs --wasm --sym -v
npx snarkjs r1cs export json circuit.r1cs circuit.r1cs.json
# Process unconstrained variables
python transform_r1cs.py

# Do a local trusted setup, generate params.bin
zkutil setup -c ./circuit.r1cs.json

# Export proving and verifying keys compatible with snarkjs
zkutil export-keys

# generate and verify proof
npx snarkjs calculatewitness # witness is still generated by snarkjs
# Transform binary witness to json
node print_wtns.mjs > witness.json
zkutil prove -c ./circuit.r1cs.json
zkutil verify

